[package]
name = "nueva-eternia-kernel"
version = "2.1.0"
edition = "2021"

[[bin]]
name = "brains"
path = "brains.rs"

[dependencies]
# Agrega aquÃ­ dependencias si las necesitas en el futuro
# xxhash-rust = "0.8"
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
